name: Pull Request Stats

on:
  push:
    branches: [ master, 'Release-*' ]
    tags: [ 'v*' ]
  release:
    types: [released]
  # Triggers the workflow only when merging pull request to the branches.
  pull_request:
    types: [opened, closed]
    branches: [ master, 'Release-*', '*' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        period: 365
